aws_region         = "us-east-1"
env_prefix         = "nginx-ha"
vpc_cidr_block     = "10.0.0.0/16"
subnet_cidr_block  = "10.0.1.0/24"
availability_zone  = "us-east-1a"
instance_type      = "t2.micro"
