[frontend]
frontend_server_ip ansible_ssh_user=ubuntu

[backend]
backend_server_1_ip ansible_ssh_user=ubuntu
backend_server_2_ip ansible_ssh_user=ubuntu
backend_server_3_ip ansible_ssh_user=ubuntu

[all:vars]
ansible_ssh_private_key_file=/path/to/private/key